#' Define Web Map Service (WMS) parameters for different map layers and basemaps.
#'
#' This function defines a set of WMS parameters for various map layers and basemaps. The parameters include information such as the layer name, URL of the WMS server, version, format, style, and more. These parameters are organized into a list, making it easy to configure and access them for map display and legend generation.
#'
#' @return A list containing WMS parameters for different map layers and basemaps.
#'
#' @examples
#' # Retrieve WMS parameters for a specific map layer
#' wms_params <- params_wms()
#' metric_wms_params <- wms_params$metric
#'
#' # Access specific WMS parameters
#' metric_name <- metric_wms_params$name
#' metric_url <- metric_wms_params$url
#'
#' @export
params_wms <- function(){
  wms <- list(metric = list(name = "Métrique",
                            url = Sys.getenv("GEOSERVER"),
                            language = "",
                            service = "WMS",
                            version = "1.0.0",
                            sld_version = "",
                            layer = "mapdo:network_metrics",
                            format = "image/png",
                            sld = "",
                            style = "", # no style, sld_body define style and legend
                            attribution = "CNRS - EVS",
                            basemap = FALSE,
                            overlayer = FALSE),
              class = list(name = "Style Fluvial",
                           url = Sys.getenv("GEOSERVER"),
                           language = "",
                           service = "WMS",
                           version = "1.1.0",
                           sld_version = "",
                           layer = "mapdo:network_metrics",
                           format = "image/png",
                           sld = "",
                           style = "", # no style, will be defined depending on selection
                           attribution = "CNRS - EVS",
                           basemap = FALSE,
                           overlayer = FALSE),
              background = list(name = "Background",
                                url = Sys.getenv("GEOSERVER"),
                                language = "",
                                service = "WMS",
                                version = "1.1.0",
                                sld_version = "",
                                layer = "mapdo:network_metrics",
                                format = "image/png",
                                sld = "",
                                style = "mapdo:classes_proposed_strahler",
                                attribution = "CNRS - EVS",
                                basemap = FALSE,
                                overlayer = FALSE),
              carteign = list(name = "Plan IGN",
                              url = 'https://data.geopf.fr/wmts?REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&STYLE={style}&TILEMATRIXSET=PM&FORMAT={format}&LAYER=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}',
                              language = "",
                              service = "WMTS",
                              version = "",
                              sld_version = "",
                              layer = "GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2",
                              format = "image/png",
                              sld = "",
                              style = "normal",
                              attribution = "IGN-F/Géoportail",
                              basemap = TRUE,
                              overlayer = FALSE),
              ortho = list(name = "Satellite IGN",
                           url = 'https://data.geopf.fr/wmts?REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&STYLE={style}&TILEMATRIXSET=PM&FORMAT={format}&LAYER=ORTHOIMAGERY.ORTHOPHOTOS&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}',
                           language = "",
                           service = "WMTS",
                           version = "",
                           sld_version = "",
                           layer = "HR.ORTHOIMAGERY.ORTHOPHOTOS",
                           format = "image/jpeg",
                           sld = "",
                           style = "normal",
                           attribution = "IGN-F/Géoportail",
                           basemap = TRUE,
                           overlayer = FALSE),
              # elevation = list(name = "Elévation IGN",
              #                  url = 'https://data.geopf.fr/wms-r?REQUEST=GetTile&SERVICE=WMS&VERSION=1.3.0&STYLE={style}&TILEMATRIXSET=PM&FORMAT={format}&LAYER=ELEVATION.ELEVATIONGRIDCOVERAGE.HIGHRES&tilePixelRatio=0',
              #                  language = "",
              #                  service = "WMS",
              #                  version = "",
              #                  sld_version = "",
              #                  layer = "ELEVATION.ELEVATIONGRIDCOVERAGE.HIGHRES",
              #                  format = "image/jpeg",
              #                  sld = "",
              #                  style = "normal",
              #                  attribution = "IGN-F/Géoportail",
              #                  basemap = TRUE,
              #                  overlayer = FALSE),
              landuse = list(name = "Occupation du sol",
                             url = Sys.getenv("GEOSERVER"),
                             language = "",
                             service = "WMS",
                             version = "1.0.0",
                             sld_version = "",
                             layer = "mapdo:mapdo_landuse_1m",
                             format = "image/png",
                             sld = "",
                             style = "mapdo:MAPDO landuse",
                             attribution = "CNRS - EVS",
                             basemap = TRUE,
                             overlayer = FALSE),
              geologie = list(name = "Géologie",
                              url = "http://geoservices.brgm.fr/geologie",
                              language = "",
                              service = "WMS",
                              version = "",
                              sld_version = "",
                              layer = "GEOLOGIE",
                              format = "image/png",
                              sld = "",
                              style = "",
                              attribution = "BRGM",
                              basemap = TRUE,
                              overlayer = FALSE),
              detrend_dem = list(name = "MNT détendancé",
                                 url = Sys.getenv("GEOSERVER"),
                                 language = "",
                                 service = "WMS",
                                 version = "1.0.0",
                                 sld_version = "",
                                 layer = " 	mapdo:mapdo_nearest_height_hillshade_1m ",
                                 format = "image/png",
                                 sld = "",
                                 style = "",
                                 attribution = "CNRS - EVS",
                                 basemap = FALSE,
                                 overlayer = TRUE),
              valley_bottom = list(name = "Fond de vallée",
                                   url = Sys.getenv("GEOSERVER"),
                                   language = "",
                                   service = "WMS",
                                   version = "1.0.0",
                                   sld_version = "",
                                   layer = "mapdo:mapdo_valley_bottom_1m",
                                   format = "image/png",
                                   sld = "",
                                   style = "mapdo:MAPDO valley bottom",
                                   attribution = "CNRS - EVS",
                                   basemap = FALSE,
                                   overlayer = TRUE),
              continuity = list(name = "Continuité latérale",
                                url = Sys.getenv("GEOSERVER"),
                                language = "",
                                service = "WMS",
                                version = "1.0.0",
                                sld_version = "",
                                layer = "mapdo:mapdo_continuity_1m",
                                format = "image/png",
                                sld = "",
                                style = "mapdo:MAPDO continuity",
                                attribution = "CNRS - EVS",
                                basemap = FALSE,
                                overlayer = TRUE),
              inondation = list(name = "Zone inondable débordement centenale",
                                url = "https://georisques.gouv.fr/services",
                                language = "fre",
                                service = "WMS",
                                version = "1.3.0",
                                sld_version = "1.1.0",
                                layer = "ALEA_SYNT_01_02MOY_FXX",
                                format = "image/png",
                                sld = "",
                                style = "inspire_common:DEFAULT",
                                attribution = "Georisques",
                                basemap = FALSE,
                                overlayer = TRUE),
              ouvrage_protection = list(name = "Ouvrage protection inondation",
                                        url = "https://georisques.gouv.fr/services",
                                        language = "fre",
                                        service = "WMS",
                                        version = "1.3.0",
                                        sld_version = "1.1.0",
                                        layer = "OUV_PROTECTION_FXX",
                                        format = "image/png",
                                        sld = "",
                                        style = "inspire_common:DEFAULT",
                                        attribution = "Georisques",
                                        basemap = FALSE,
                                        overlayer = TRUE)
  )
  return(wms)
}
